name: Build and Release .exe

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"

      - name: Build
        run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=Link -o output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/GameLibsMaker.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
